// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TraderJoe.MainSystem.TradingEngine.DataAccess;

#nullable disable

namespace TraderJoe.MainSystem.TradingEngine.Migrations
{
    [DbContext(typeof(TradingEngineDbContext))]
    [Migration("20260605023544_AddEventTimestamp")]
    partial class AddEventTimestamp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TradeRequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TradeRequestId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.SymbolPriceStateEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AskPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BidPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentMarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventTimestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousMarketPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Spread")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SpreadPercent")
                        .HasColumnType("TEXT");

                    b.HasKey("Symbol");

                    b.ToTable("SymbolPriceStates");
                });

            modelBuilder.Entity("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.TradeRequestEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Side")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey");

                    b.ToTable("TradeRequests");
                });

            modelBuilder.Entity("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.TradingRulesEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AutoTradingSpreadThresholdPercent")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDuplicateOrderIdCheckEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSymbolWhitelistEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MaxNotionalValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxPriceDeviationPercent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MaxQuantityPerOrder")
                        .HasColumnType("TEXT");

                    b.Property<string>("SymbolWhitelist")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TradingRules");
                });

            modelBuilder.Entity("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.OrderEntity", b =>
                {
                    b.HasOne("TraderJoe.MainSystem.TradingEngine.DataAccess.Entities.TradeRequestEntity", "TradeRequest")
                        .WithMany()
                        .HasForeignKey("TradeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TradeRequest");
                });
#pragma warning restore 612, 618
        }
    }
}
